version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: weekly

updates:
  - package-ecosystem: github-actions
    directory: /
    cooldown:
      default-days: 7
    patterns:
      - "*"
    multi-ecosystem-group: all-dependencies

  - package-ecosystem: npm
    directory: /
    cooldown:
      default-days: 7
    patterns:
      - "*"
    multi-ecosystem-group: all-dependencies

  - package-ecosystem: cargo
    directory: /src-tauri
    cooldown:
      default-days: 7
    patterns:
      - "*"
    multi-ecosystem-group: all-dependencies
