// SPDX-FileCopyrightText: 2026 Game Buddy
// SPDX-License-Identifier: AGPL-3.0-only

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const versionPath = resolve(root, "VERSION");
const version = process.argv[2] ?? readFileSync(versionPath, "utf8").trim();

const semverPattern =
  /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$/;

function isValidSemver(version) {
  const match = semverPattern.exec(version);
  if (!match) return false;

  return !(match[4] ?? "").split(".").some((identifier) => {
    if (identifier.length < 2 || !identifier.startsWith("0")) return false;
    return [...identifier].every(
      (character) => character >= "0" && character <= "9",
    );
  });
}

if (!isValidSemver(version)) {
  console.error(`Invalid semantic version: ${version}`);
  process.exit(1);
}

function read(relativePath) {
  return readFileSync(resolve(root, relativePath), "utf8").replace(
    /\r\n?/g,
    "\n",
  );
}

function write(relativePath, contents) {
  writeFileSync(resolve(root, relativePath), contents);
}

function replaceExactly(relativePath, pattern, replacement) {
  const contents = read(relativePath);
  if (!pattern.test(contents)) {
    throw new Error(`Could not update version in ${relativePath}`);
  }

  const updated = contents.replace(pattern, replacement);
  if (updated !== contents) write(relativePath, updated);
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function expectedVersions() {
  return new Map([
    ["package.json", JSON.parse(read("package.json")).version],
    [
      "src-tauri/Cargo.toml",
      read("src-tauri/Cargo.toml").match(/^version = "([^"]+)"$/m)?.[1],
    ],
    [
      "src-tauri/tauri.conf.json",
      JSON.parse(read("src-tauri/tauri.conf.json")).version,
    ],
    [
      "src/version.ts",
      read("src/version.ts").match(
        /^export const APP_VERSION = "([^"]+)";$/m,
      )?.[1],
    ],
  ]);
}

function checkVersions() {
  const sourceVersion = readFileSync(versionPath, "utf8").trim();
  if (!isValidSemver(sourceVersion)) {
    throw new Error(`Invalid semantic version in VERSION: ${sourceVersion}`);
  }

  const versions = expectedVersions();
  const mismatches = [...versions].filter(
    ([, fileVersion]) => fileVersion !== sourceVersion,
  );

  const lockfile = read("src-tauri/Cargo.lock");
  const lockVersion = lockfile.match(
    /\[\[package\]\]\r?\nname = "gganbu-app-bridge"\r?\nversion = "([^"]+)"/,
  )?.[1];
  if (lockVersion !== sourceVersion) {
    mismatches.push(["src-tauri/Cargo.lock", lockVersion]);
  }

  const changelogHeading = new RegExp(
    `^## \\[${escapeRegExp(sourceVersion)}\\](?:\\s+-\\s+\\d{4}-\\d{2}-\\d{2})?\\s*$`,
    "m",
  );
  if (!changelogHeading.test(read("CHANGELOG.md"))) {
    mismatches.push(["CHANGELOG.md", `missing ## [${sourceVersion}] heading`]);
  }

  if (mismatches.length > 0) {
    for (const [filePath, fileVersion] of mismatches) {
      console.error(
        `${filePath}: expected ${sourceVersion}, found ${fileVersion ?? "missing"}`,
      );
    }
    process.exit(1);
  }

  console.log(`All application versions match ${sourceVersion}`);
}

if (process.argv[2] === undefined) {
  checkVersions();
} else {
  write("VERSION", `${version}\n`);
  replaceExactly("package.json", /("version": ")[^"]+(",)/, `$1${version}$2`);
  replaceExactly(
    "src-tauri/Cargo.toml",
    /(^version = ")[^"]+("$)/m,
    `$1${version}$2`,
  );
  replaceExactly(
    "src-tauri/tauri.conf.json",
    /("version": ")[^"]+(",)/,
    `$1${version}$2`,
  );
  replaceExactly(
    "src-tauri/Cargo.lock",
    /(\[\[package\]\]\r?\nname = "gganbu-app-bridge"\r?\nversion = ")[^"]+/,
    `$1${version}`,
  );
  write(
    "src/version.ts",
    `// SPDX-FileCopyrightText: 2026 Game Buddy\n// SPDX-License-Identifier: AGPL-3.0-only\n\n// Generated by pnpm version:set. Do not edit.\nexport const APP_VERSION = "${version}";\n`,
  );
  console.log(`Updated application version to ${version}`);
  checkVersions();
}
